[workspace]
members = [
    "kernel",
    "driver",
    "application",
    "client",
]

[workspace.package]
license = "AGPL-3.0-or-later"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
orbital = "0.1"